services:
  - type: web service
    name: code-save-and-share
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot1.py
    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: STORAGE_CHANNEL_ID
        sync: false

      - key: MAX_FILE_SIZE_MB
        value: "50"
