services:
  - type: worker
    name: krutik-ultimate-bot-hosting
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot1.py
    autoDeploy: true
    
